
-- Ranking based on Volume: 
Ranking based on volume = 

VAR _topprod = RANKX(
    FILTER(ALL(DimProduct[ProductName]), NOT(ISBLANK(DimProduct[ProductName]))), 
    [Sales Volume],
    ,
    DESC
)

VAR _bottomprod = RANKX(
    FILTER(ALL(DimProduct[ProductName]), NOT(ISBLANK(DimProduct[ProductName]))), 
    [Sales Volume],
    ,
    ASC
)

VAR _ranking = IF(SELECTEDVALUE(TopBottom[Value]) = "Top", _topprod, _bottomprod)

RETURN
IF(_ranking <= 'Ranking Option'[Ranking Option Value], [Sales Volume])


-- Net Sales: 
Net Sales = 
SUMX(FactSales, FactSales[UnitPrice] * FactSales[SalesQuantity] - FactSales[DiscountAmount])

-- Standard Margin: 
Standard Margin = DIVIDE([Standard Margin], [Net Sales], 0)

-- Profit
Profit = [Net Sales] - [COGS]

-- COGS (Cost of Goods Sold): 
COGS = SUMX(FactSales, FactSales[UnitCost] * FactSales[SalesQuantity])

-- Orders (Online): 
orders_online_people = COUNT(FactOnlineSales[CustomerKey])

-- Total Customers:
Total Customers = DISTINCTCOUNT(FactOnlineSales[CustomerKey])

-- Total Online Orders: 
Total Online Orders = COUNTROWS(FactOnlineSales)

-- Average Orders per Customer: 
Average Orders per Customer = [Total Online Orders] / [Total Customers]

-- Total Customers by Occupation:
Total Customers by Occupation = COUNT(FactOnlineSales[CustomerKey])

-- Calendar Table (basic structure):
Calendar = 
ADDCOLUMNS ( 
    CALENDAR ( MINX ( FactSales, FactSales[NewDate] ), MAXX ( FactSales, FactSales[NewDate] ) ),
    "DateAsInteger", FORMAT ( [Date], "YYYYMMDD" ),
    "Year", YEAR ( [Date] ),
    "MonthNo", FORMAT ( [Date], "MM" ), 
    "YearMonthNum", FORMAT ( [Date], "YYYY/MM" ), 
    "YearMonth", FORMAT ( [Date], "YYYY/mmm" ), 
    "Month_Short", FORMAT ( [Date], "mmm" ),
    "MOnth_Long", FORMAT ( [Date], "mmmm" ),
    "WeekNo", WEEKDAY ( [Date] ),
    "Weekdays", FORMAT ( [Date], "dddd" ),
    "WeekDayShort", FORMAT ( [Date], "ddd" ),
    "Quartal", "Q" & FORMAT ( [Date], "Q" ),
    "YearQuartal", FORMAT ( [Date], "YYYY" ) & "/Q" & FORMAT ( [Date], "Q" )
)

